version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --workers 3 school_management.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] *
    restart: always
