# Generated by Django 5.2.14 on 2026-06-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
    ]
