# Generated by Django 5.2.14 on 2026-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. M.Sc. Mathematics, B.Ed.', max_length=200, null=True),
        ),
    ]
