# Generated by Django 6.0.6 on 2026-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_attendance_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
