# Generated by Django 5.2.14 on 2026-06-23 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_studentwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(blank=True, help_text='The main class teacher for this classroom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classroom', to='school.teacher'),
        ),
    ]
