# Generated by Django 5.2.14 on 2026-06-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_timetable_day_alter_timetable_period_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'classroom', 'subject', 'date')},
        ),
    ]
