# Generated by Django 5.2.14 on 2026-06-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_teacherwarning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.teacher'),
        ),
    ]
